### ISSUE TITLE
sci-libs/gdcm 2.8.4 fails to compile with poppler 0.68.0

### ISSUE THREAD

**Issue by ahilke** [gerddie/gentoo-imaging#19]
I just updated to app-text/poppler 0.68.0, since it is now marked as stable, but sci-libs/gdcm 2.8.4 fails to compile with the following error:

	[ 87%] Building CXX object Source/MessageExchangeDefinition/CMakeFiles/gdcmMEXD.dir/gdcmAsynchronousOperationsWindowSub.cxx.o
	cd /var/tmp/portage/sci-libs/gdcm-2.8.4/work/gdcm-2.8.4_build/Source/MessageExchangeDefinition && /usr/bin/x86_64-pc-linux-gnu-g++ -DgdcmMEXD_EXPORTS -I/var/tmp/portage/sci-libs/gdcm-2.8.4/work/gdcm-2.8.4_build/Source/Common -I/var/tmp/portage/sci-libs/gdcm-2.8.4/work/gdcm-2.8.4/Source/Common -I/var/tmp/portage/sci-libs/gdcm-2.8.4/work/gdcm-2.8.4/Source/DataStructureAndEncodingDefinition -I/var/tmp/portage/sci-libs/gdcm-2.8.4/work/gdcm-2.8.4/Source/DataDictionary -I/var/tmp/portage/sci-libs/gdcm-2.8.4/work/gdcm-2.8.4/Source/InformationObjectDefinition -I/var/tmp/portage/sci-libs/gdcm-2.8.4/work/gdcm-2.8.4/Source/MediaStorageAndFileFormat -I/var/tmp/portage/sci-libs/gdcm-2.8.4/work/gdcm-2.8.4_build/Testing/Source/Data -I/var/tmp/portage/sci-libs/gdcm-2.8.4/work/gdcm-2.8.4/Testing/Source/Data -I/var/tmp/portage/sci-libs/gdcm-2.8.4/work/gdcm-2.8.4/Utilities -I/var/tmp/portage/sci-libs/gdcm-2.8.4/work/gdcm-2.8.4/Utilities/socketxx -I/var/tmp/portage/sci-libs/gdcm-2.8.4/work/gdcm-2.8.4/Utilities/socketxx/socket++ -I/var/tmp/portage/sci-libs/gdcm-2.8.4/work/gdcm-2.8.4_build/Utilities/socketxx/socket++   -DNDEBUG -O2 -march=native -pipe -fomit-frame-pointer -std=c++11 -fPIC   -o CMakeFiles/gdcmMEXD.dir/gdcmAsynchronousOperationsWindowSub.cxx.o -c /var/tmp/portage/sci-libs/gdcm-2.8.4/work/gdcm-2.8.4/Source/MessageExchangeDefinition/gdcmAsynchronousOperationsWindowSub.cxx
	/var/tmp/portage/sci-libs/gdcm-2.8.4/work/gdcm-2.8.4/Applications/Cxx/gdcmpdf.cxx: In function ‘std::__cxx11::string getInfoDate(Dict*, const char*)’:
	/var/tmp/portage/sci-libs/gdcm-2.8.4/work/gdcm-2.8.4/Applications/Cxx/gdcmpdf.cxx:52:36: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
	     s = obj.getString()->getCString();
	         ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
	/var/tmp/portage/sci-libs/gdcm-2.8.4/work/gdcm-2.8.4/Applications/Cxx/gdcmpdf.cxx: In function ‘std::__cxx11::string getInfoString(Dict*, const char*, UnicodeMap*, GBool&)’:
	/var/tmp/portage/sci-libs/gdcm-2.8.4/work/gdcm-2.8.4/Applications/Cxx/gdcmpdf.cxx:120:23: error: invalid conversion from ‘const GooString*’ to ‘GooString*’ [-fpermissive]
	     s1 = obj.getString();
	          ~~~~~~~~~~~~~^~

When downgrading poppler to the last stable version, 0.62.0-r1, gdcm 2.8.4 builds successfully.

Find the whole log file here: [build.log](https://github.com/gerddie/gentoo-imaging/files/2737096/build.log)

**Comment by gerddie** [comment]
I'll push the ebuild for v2.8.8 shortly, that should fix this.

**Comment by ahilke** [comment]
Thanks for the quick reply. gdcm 2.8.8 works fine. But it seems like you forgot to recreate the manifest after deleting the 2.8.4 ebuild (I had to recreate it locally).

**Comment by gerddie** [comment]
Corrected, actually you just got lucky, I was already looking into pushing gdcm-2.8.8 ;)
